(defhydra hydra-emacs (global-map "<f8>")
  "What would like to do?"
	("e" my-emacs-todo-files "todo")
  ("f" my-emacs-projectile-find-file "file")
	("i" my-emacs-init-file "init")
  ("b" my-emacs-bindings-file "bindings")
  ("x" my-emacs-reexecute-bindings-file "execute bindings"))

(defhydra hydra-window-management (global-map "C-x w")
  "window"
  ("<left>" windmove-left)
  ("<right>" windmove-right)
  ("<down>" windmove-down)
  ("<up>" windmove-up)
  ("|" my-toggle-window-split)
  ("0" delete-window "nuke")
  ("1" delete-other-windows "delete-other-windows")
  ("2" double-window "double")
  ("b" split-window-below "below")
  ("b" switch-to-buffer-other-window "switch")
	("d" delete-window "nuke")
	("y" delete-other-windows "delete-other-windows")	
  ("f" find-file "file")
  ("F" find-file-other-window "F")
  ("h" split-window-horizontally "horizontally")
	("k" delete-window "nuke")
  ("s" split-window-horizontally "horizontally")	
  ("m" maximize-window "maximize")
  ("o" other-window "other")
  ("q" nil)
  ("r" split-window-right "right")
  ("w" crux-swap-windows "swap")
  ("t" crux-transpose-windows "transpose") 
  ("v" split-window-vertically "vertically")
  ("f" hydra-frame-management/body "frame"))

(defhydra hydra-frame-management (global-map "C-x a")
  "frame" 
  ("<left>" move-frame-left)
  ("<right>" move-frame-right)
  ("<down>" move-frame-down)
  ("<up>" move-frame-up)
  ("E" enlarge-frame "enlarge-frame")
  ("S" shrink-frame "shrink-frame")
  ("b" switch-to-buffer-other-frame "switch-to-buffer-other-frame")
  ("d" delete-frame "delete-frame")  
  ("d" dired-other-frame "dired-other-frame")	
  ("e" enlarge-frame-horizontally "enlarge-frame-horizontally")
	("k" delete-frame "kill-frame")
	("0" delete-frame "kill-frame")    
  ("n" make-frame "make-frame")  
  ("o" other-frame "other-frame")
  ("q" nil)
  ("s" shrink-frame-horizontally "shrink-frame-horizontally")
  ("w" hydra-window-management/body "window"))

(defhydra hydra-startup (global-map "C-x C-x")
  "What would like to do?"
	("t" org-todo-list "org-todo-list")
  ("j" my-open-my-japanese-file "japanese"))

(defhydra hydra-text-scale (global-map "C-x C-=")
  "text scale"
  ("i" text-scale-increase "increase")
  ("d" text-scale-decrease "decrease"))

(provide 'bindings-hydras)
